FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /listener
COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# listener
    # listener
        #...
    # tele_bot
        #...
